### 🧠 What Is NumPy?
- NumPy (short for Numerical Python) is a fundamental Python library for numerical computing. It provides:

- Multidimensional array objects (ndarrays) for efficient storage and manipulation of numerical data.

- A vast collection of mathematical functions to operate on these arrays.

- Tools for integrating C/C++ and Fortran code, making it a cornerstone for scientific computing in Python.

In [1]:
import numpy as np

### Array 

- np.array() is used to create a NumPy array, known as an ndarray.

- Unlike Python lists, NumPy arrays are homogeneous, meaning all elements must be of the same data type (e.g., all integers, all floats).

- It allows fast and vectorized operations across entire arrays.

In [2]:
arrray = np.array([1,2,3,4])

print(arrray)
print(type(arrray))
print(type(arrray[0]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


### `np.arange` 

- Create an array of some size with gap between the works like `range()`

Syntax : ` np.arange(start , stop , step)`

In [3]:
print(np.arange(5))

print(np.arange(1, 10, 2))

np_arange = np.arange(1, 10, 2)
print(type(np_arange))

[0 1 2 3 4]
[1 3 5 7 9]
<class 'numpy.ndarray'>


### np.linespace

- used to create array of any size with gap of ame number of no.s between them 

Syntax : `np.linespace(start, stop , num = x)`

In [6]:
np_linspace = np.linspace(1,100,100)
print(np_linspace)
print(type(np_linspace))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]
<class 'numpy.ndarray'>


### np.zeroshape

- used to show the dimension of array 
- `np.ndim` tells how many dimensions 

In [7]:
npz_2 = np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
