# NumPy Array Creation & Properties

### 1. **`np.zeros(shape)`**
   - Creates an array filled with zeros.

In [2]:
import numpy as np

np.zeros(3)

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 2. **`np.full(shape, fill_value)`**
   - Creates an array of given shape filled with a specified value.

In [3]:
np.full((4,5), 1)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 3. **`np.eye(n)`**
   - Creates an identity matrix of size `n x n`.
   - Diagonal has 1s, rest are 0s.

In [4]:
np.eye(5)

np.eye(5,3) # creates identity matrix with 1's in the diagonal and 0's elsewhere, with 5 rows and 3 columns



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:

np.eye(5,5,-1) # creates identity matrix with 1's in the diagonal and 0's elsewhere, with 5 rows and 5 columns, but shifted by -1 (one row up)


array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### 4. **`np.empty(shape)`**
   - Returns a new array of given shape, without initializing entries (may contain garbage values).

In [6]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])


### 5. **`np.random.rand(d1, d2, ...)`**
   - Generates an array with random floats in the range [0.0, 1.0).
   - Example: `np.random.rand(2, 3)` → 2x3 matrix of random floats

In [7]:
np.random.rand(3,3)

array([[0.9329812 , 0.46299662, 0.07891255],
       [0.83691381, 0.71345438, 0.37640926],
       [0.92916848, 0.24119187, 0.92788976]])

### 6. **`np.random.randint(start, end, size)`**
   - Returns random integers from `start` (inclusive) to `end` (exclusive).
   - Example: `np.random.randint(0, 10, (2, 3))` → 2x3 matrix of ints between 0–9


In [8]:
arr  = np.random.randint(0, 10 , (4,3))

### 7. **`array.itemsize`**
   - Returns the size (in bytes) of one array element.
   - Example: `arr.itemsize` → size of a single element

In [9]:
arr.itemsize


4


### 8. **`array.nbytes`**
   - Returns the total number of bytes consumed by the array.
   - Equals `itemsize * size`.


In [10]:
arr.nbytes

48

### 9. **`array.T`**
   - Returns the transpose of the array (only works on 2D or higher).
   - Example: `arr.T`

In [11]:
print(arr)

b = arr.T
print(   )


print(b)

[[9 4 8]
 [6 2 8]
 [2 0 7]
 [3 6 1]]

[[9 6 2 3]
 [4 2 0 6]
 [8 8 7 1]]


### 10. Indexing & Slicing
- Access subsets of arrays using slicing.
- Syntax: `array[start:stop:step]`
- Example: `mat[1:3, ::2]` → rows 1 to 2, every second column


In [12]:
c = np.array([1,2,3])

print(c[1])

2


In [16]:
a = np.random.randint(0,10 , (3,3))

print(a)


[[1 0 9]
 [6 0 1]
 [3 9 6]]


In [ ]:
print(a[1,2])  # Accessing element at row 1, column 2

print(a[1:3, 0:2]) # Slicing rows 1 to 2 and columns 0 to 1

1
[[6 0]
 [3 9]]


### 11. Boolean Indexing
- Filter elements based on condition.
- Example: `arr > 10` returns a boolean array

In [19]:
print(c>0)

[ True  True  True]


### 12. `np.where(condition)`
- Returns indices where the condition is `True`.
- Example: `np.where(arr > 20)` → indices where element > 20

In [23]:
print(np.where(a >5))

(array([0, 1, 2, 2]), array([2, 0, 1, 2]))


### 13. Reshaping vs Resizing

#### `arr.reshape(new_shape)`
- Changes the shape without changing data.
- Fails if total size mismatches.
- Example: `arr.reshape(2, 3)`

#### `arr.resize(new_shape)`
- Resizes array and fills extra places with `0` if needed.
- Changes the original array in-place.

In [25]:
a.reshape(1,11)

ValueError: cannot reshape array of size 9 into shape (1,11)

In [28]:
a= np.resize(1,11)

print(a)

[1 1 1 1 1 1 1 1 1 1 1]


### 14. Flattening Arrays
- `arr.flatten()` → Converts any N-D array to 1-D array.
- Does **not** affect the original array.

In [32]:
arr = np.random.randint(0,10 , (3,3))

print(arr)

arr.flatten()

[[5 0 4]
 [1 1 4]
 [7 4 4]]


array([5, 0, 4, 1, 1, 4, 7, 4, 4], dtype=int32)

### 15. Shape Attribute
- `arr.shape` → Returns the shape of the array as a tuple.
- Example: `(3, 4)` means 3 rows, 4 columns

In [33]:
arr.shape

(3, 3)

### 16. `np.squeeze()`
- Removes dimensions of size 1.
- Useful for converting shapes like `(1, 4, 1)` to `(4,)`.


In [36]:
narr = np.full(((3,3)), 1)

print(narr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [39]:
narr.squeeze()

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### 17. Summing Across Axis

#### `np.sum(arr, axis=0)`
- Column-wise sum (downward direction)

#### `np.sum(arr, axis=1)`
- Row-wise sum (horizontal direction)

In [46]:
arra = np.random.randint(0,10 , (3,3))

print(arra)
print(   )
print(np.sum(arra , axis=0))  # Sum along columns

print(np.sum(arra , axis=1))  # Sum along rows

[[3 4 2]
 [2 1 9]
 [3 6 1]]

[ 8 11 12]
[ 9 12 10]
