# NumPy Mathematical Operations

In **pure Python**, adding two lists results in **concatenation**, not element-wise addition:

In [1]:
a = [1,2,3]
b = [4,5,6]

print(a+b)

[1, 2, 3, 4, 5, 6]


## 🔹 Why NumPy?
- With NumPy arrays, you can perform vectorized operations — arithmetic and logical — directly between arrays:

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)     
print(a - b)     
print(a * b)     
print(a / b)     


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## 🔸 Comparison Operations
- These return a boolean array:

In [3]:
print(a > b )
print(a< b)
print(a == b)


[False False False]
[ True  True  True]
[False False False]


## 🔸 Bitwise Operations
- Useful for binary-level manipulation:

In [4]:
print(a & b)     # Bitwise AND
print(a | b)     # Bitwise OR


[0 0 2]
[5 7 7]


## 🔸 Modulus and Power

In [6]:
print(a ** b)
print(a % b)      

[  1  32 729]
[1 2 3]


## 🔸Common Math Functions :

In [8]:
a = np.array([1, 2, 3, 4])

print(np.sqrt(a))  # Square root
print(np.exp(a))    # Exponential   
print(np.log(a))    # Natural logarithm
print(np.sin(a))    # Sine

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


## 🔸Matrix Operations : 

- Element Wise Multiplication
- In NumPy, **element-wise multiplication** is performed when both matrices (arrays) have the **same shape**.
- Each element from the first array is multiplied by the corresponding element in the second array.

In [11]:
units = np.array([10 , 49 , 22 , 5])

profit = np.array([100, 200, 150, 300])

print(units * profit)

print(np.sum(units * profit))  # Total profit

[1000 9800 3300 1500]
15600


## 🔸 Matrix Multiplication (Dot Product)
- If you want traditional matrix multiplication:

- 🔁 Requirements for Element-wise Multiplication

- 1 matrix's row should be equal to another matrixs column like 2 x 3 * 3 x 2

- Broadcasting can be used if shapes are compatible

-- 

- dot_result = np.dot(a, b)
 - OR
- dot_result = a @ b


In [19]:
m1 = np.array([
    [10 , 20, 30],
    [40 , 50, 60],
    [70 , 80, 90],
    [100 , 110, 120]
])

m2 = np.array([ 5 , 4, 3])

print(m1.shape)

print(m2.shape)

print(m1 @ m2)  # Matrix multiplication

(4, 3)
(3,)
[ 220  580  940 1300]


# 📡 NumPy Broadcasting

## 🔹 What is Broadcasting?

Broadcasting in NumPy allows **arithmetic operations** on arrays of **different shapes** by **automatically expanding** one array to match the shape of the other — **without actually copying data**.

Instead of throwing an error, NumPy uses broadcasting rules to **stretch the smaller array** across the larger one when compatible.

In [20]:

a = np.array([2, 3, 4, 5])
b = 10

print(a + b)  # [12 13 14 15]


[12 13 14 15]


## 🔹creating array from existing data :

- like list tuple etc

In [25]:
a = [2, 3, 4, 5]

b = (10, 20, 30, 40)

print(type(a))

print(type(b))

a_ar = np.array(a)
b_ar = np.array(b)
print(a_ar.dtype)  
print(b_ar.dtype)

<class 'list'>
<class 'tuple'>
int64
int64


## 🔹Vstack and Hstack

In [27]:
a = np.array([2, 3, 4, 5])
b = np.array([10, 20, 30, 40])

print(np.vstack((a, b)))  # Vertical stack
print(np.hstack((a, b)))  # Horizontal stack

[[ 2  3  4  5]
 [10 20 30 40]]
[ 2  3  4  5 10 20 30 40]


## 🔹 Statistical Functions

In [28]:
data = np.array([10 , 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data))
print("Max:", np.max(data))

Mean: 55.0
Median: 55.0
Standard Deviation: 28.722813232690143
Variance: 825.0
Min: 10
Max: 100


In [29]:
print("Argmin:", np.argmin(data))
print("Argmax:", np.argmax(data))

Argmin: 0
Argmax: 9


In [30]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print(np.mean(matrix, axis=0))
print(np.mean(matrix, axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [31]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50)) # range 1 - 100
print(np.quantile(data, 1)) # range 0 - 1

5.0
9


In [32]:
arr = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])

print("Sorted:", np.sort(arr))
print("Sorted indices:", np.argsort(arr))
print("Insert 4 position:", np.searchsorted(np.sort(arr), 4))
print("Unique elements:", np.unique(arr))
print("Count of each element:", np.bincount(arr))

Sorted: [1 1 1 1 2 3 5 6 6 8]
Sorted indices: [3 2 5 4 7 0 8 1 9 6]
Insert 4 position: 6
Unique elements: [1 2 3 5 6 8]
Count of each element: [0 4 1 1 0 1 2 0 1]
